### ISSUE TITLE
Bug Error When Attempting to Run Test Data

### ISSUE THREAD

**Issue by bioinfonerd** [ribosomeprofiling/riboflow#5] opened 2020-01-21 22:02 UTC
Riboflow looks like potentially a powerful tool so I tried downloading and seeing if I could run the tool.  It looks like there is a file missing, but I'm unsure what?  I have attached the output [log.txt](https://github.com/ribosomeprofiling/riboflow/files/4093929/log.txt) of the Next flow run.

**Comment by hakanozadam** [comment] 2020-01-21 22:48
It seems like RiboFlow couldn't find the test data.

Could you look at the structure of the foder `/home/njohnson/local/rf_test_run/riboflow`?
For example:
```
tree /home/njohnson/local/rf_test_run/riboflow
```

Do you see a folder named `rf_sample_data` , with fastq files in it?

If not, could you try downloading the test data inside the riboflow folder?
```
cd /home/njohnson/local/rf_test_run/riboflow
git clone https://github.com/ribosomeprofiling/rf_sample_data.git
```
The paths in the project file are relative. So you need to be inside the `riboflow` folder to run the pipeline.

**Comment by hakanozadam** [comment] 2020-01-22 18:51
Your directory structure looks fine. The test data is where it should be. However, I am unable to reproduce this error on my end. I just did a test run from scratch and the RiboFlow pipeline successfully ran and produced ribo files. I ran the following sequence of commands. 

```
mkdir test_jan_22_2020
cd test_jan_22_2020/
git clone https://github.com/ribosomeprofiling/riboflow.git
cd riboflow/
git clone https://github.com/ribosomeprofiling/rf_sample_data.git
nextflow RiboFlow.groovy -params-file project.yaml -profile docker_local
```

My output is in this in this [file.txt](https://github.com/ribosomeprofiling/riboflow/files/4099225/nextflow_output.txt).

I did this run on an Ubuntu system and ran RiboFlow via docker `-profile docker_local`. Though it should run locally after the conda environment is activated.

**Comment by bioinfonerd** [comment] 2020-01-22 20:08
I removed everything and ran the exact same commands listed in a Ubuntu environment with the same result.  So I tried doing it via the conda route and its work perfectly using that environment.  

Any idea why running it via docker `-profile docker_local` would cause this change?

**Comment by hakanozadam** [comment] 2020-01-22 21:51
Do I understand you correctly that the command
```
nextflow RiboFlow.groovy -params-file project.yaml -profile docker_local
```
is **NOT** working for you, whereas the command 
```
nextflow RiboFlow.groovy -params-file project.yaml 
```
**IS** working? If yes, this is unexpected.

The first run (with `-profile docker_local`) runs the pipeline via a Docker container. 
The second command ( without `-profile docker_local` i.e., `nextflow RiboFlow.groovy -params-file project.yaml`) runs the pipeline directly on the local machine without using Docker.

If I understood you correctly, this is surprising to me because I would expect the Docker container would behave uniformly regardless of the platform. [The latest Docker image](https://hub.docker.com/r/ceniklab/riboflow/tags) hasn't changed for a while so we are using the same Docker image hence I don't know why `-profile docker_local` is creating problems in your case.

**Comment by hakanozadam** [comment] 2020-01-24 17:49
I am assuming that running RiboFlow via conda installation solved the problem. So I am closing this. Feel free to reopen if you encounter problems.

**Closed by hakanozadam** 2020-01-24 17:49 UTC

**Comment by bioinfonerd** [comment] 2020-01-27 18:54
Sorry for re-opening, but wanted to let you know what happened.  Running RiboFlow via conda installation worked without a hitch.  The issue with running via docker containers was due to issues on my end as the containers were not actually downloading and being used.  Once I fixed that issue, your setup works perfectly using the `-profile docker_local`.

**Comment by hakanozadam** [comment] 2020-01-27 22:49
Thank you for letting us know.

We always appreciate user feedback!
